name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: war-file
        path: /home/runner/work/eks-gitaction/eks-gitaction/webapp/target/*.war
    - name: List build directory contents
      run: ls -la /home/runner/work/eks-gitaction/eks-gitaction/webapp/target

      # adding aws config...
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

      # login ecr

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

      # build docker image

    - name: Build Docker image
      run: |
        docker build -t image-ecr .
        docker tag image-ecr:latest 536697268429.dkr.ecr.ap-south-1.amazonaws.com/image-ecr:latest

        #push image to ecr

    - name: Push Docker image to ECR
      run: docker push 536697268429.dkr.ecr.ap-south-1.amazonaws.com/image-ecr:latest





   
